name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        MANAGER_URL: ${{ secrets.MANAGER_URL }}
        API_KEY: ${{ secrets.API_KEY }}
      run: cargo test --verbose
